import { NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { calleRequest } from "@/lib/calle";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const resultSchema={type:"object",required:["summary","facts","confidence","next_step"],properties:{summary:{type:"string"},facts:{type:"array",items:{type:"string"}},confidence:{type:"string",enum:["high","medium","low","unknown"]},next_step:{type:"string"}}};
const validPhone=(v:unknown):v is string=>typeof v==="string"&&/^\+[1-9]\d{7,14}$/.test(v); const validLocale=(v:string)=>/^[A-Za-z]{2,3}(?:-[A-Za-z]{2,4})?$/.test(v);
const hits=new Map<string,{count:number,reset:number}>();
function rateLimit(request:Request){const key=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"anonymous",now=Date.now(),old=hits.get(key);if(!old||old.reset<now){hits.set(key,{count:1,reset:now+60_000});return true}if(old.count>=5)return false;old.count++;return true}
export async function POST(request:Request){
 if(process.env.CALLE_LIVE_ENABLED!=="true")return NextResponse.json({error:"Live calling is disabled. Set CALLE_LIVE_ENABLED=true only after configuring your CALL-E account and reviewing the production safety settings."},{status:503});
 if(!rateLimit(request))return NextResponse.json({error:"Too many call requests. Please wait a minute before trying again."},{status:429});
 const body=await request.json().catch(()=>null);const goal=typeof body?.goal==="string"?body.goal.trim():"",phone=body?.phone,region=typeof body?.region==="string"?body.region.toUpperCase():"IN",locale=typeof body?.locale==="string"?body.locale:"en-IN";
 if(body?.approved!==true)return NextResponse.json({error:"Explicit call authorization is required."},{status:400}); if(!goal||goal.length<12||goal.length>3000)return NextResponse.json({error:"Enter a clear task between 12 and 3000 characters."},{status:400}); if(!validPhone(phone))return NextResponse.json({error:"Use an E.164 phone number, for example +919876543210."},{status:400}); if(!/^[A-Z]{2}$/.test(region))return NextResponse.json({error:"Region must be a two-letter country code."},{status:400}); if(!validLocale(locale))return NextResponse.json({error:"Use a valid locale such as en-IN or hi-IN."},{status:400});
 const workflowId=`ab_${randomUUID()}`;const task=`You are ActionBridge, an AI phone-work executor. Clearly identify yourself as an AI assistant. Call the recipient and accomplish only this user-authorized goal: ${goal}. Do not claim to be human. Do not make purchases, financial commitments, legal commitments, or unrelated consequential commitments. Do not disclose private information beyond what is necessary. Verify important facts, distinguish confirmed information from assumptions, and return concise structured evidence. If the recipient cannot complete the task, explain why and return a safe next step.`;
 try{const r=await calleRequest("/v1/calls",{method:"POST",headers:{"Idempotency-Key":workflowId},body:JSON.stringify({task,recipients:[{phones:[phone],region,locale}],result_schema:resultSchema,recipient_result_schema:resultSchema,metadata:{product:"actionbridge",workflow:"goal-to-phone-action",workflow_id:workflowId,version:"1.1"},...(process.env.ACTIONBRIDGE_WEBHOOK_URL?{webhook_url:process.env.ACTIONBRIDGE_WEBHOOK_URL}: {})})});const data=await r.json().catch(()=>({}));if(!r.ok)return NextResponse.json({error:data?.error?.message||data?.message||"CALL-E rejected the call request.",upstreamStatus:r.status},{status:r.status>=400&&r.status<500?r.status:502});return NextResponse.json({callId:data.call_id||data.id,status:data.status||"created",workflowId,...data},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to reach CALL-E."},{status:502})}
}
