"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
type CallResponse={callId?:string;status?:string;taskCompleted?:boolean;completionConfidence?:unknown;structuredResult?:unknown;evidence?:unknown;recipients?:unknown[];error?:string};
type EventItem={id?:string;type?:string;status?:string;timestamp?:string;message?:string;[key:string]:unknown};
type View="overview"|"task"|"calls"|"results"|"history"|"settings"|"docs";
const nav:Array<[View,string,string]>=[["overview","⌂","Command Center"],["task","+","New Task"],["calls","◉","Live Calls"],["results","✓","Results & Evidence"],["history","↺","History"],["settings","⚙","Settings"],["docs","?","Documentation"]];
const terminal=new Set(["completed","failed","cancelled","canceled","error"]);
const examples=["Confirm whether the electrician can visit tomorrow morning, earliest arrival time, and total price.","Ask the service provider whether they have an appointment tomorrow and what the earliest slot costs.","Call the vendor and verify availability, price, and any conditions before I decide."];
export default function Home(){
 const [view,setView]=useState<View>("overview"),[goal,setGoal]=useState(""),[phone,setPhone]=useState(""),[region,setRegion]=useState("IN"),[locale,setLocale]=useState("en-IN"),[approved,setApproved]=useState(false),[loading,setLoading]=useState(false),[result,setResult]=useState<CallResponse|null>(null),[events,setEvents]=useState<EventItem[]>([]),[history,setHistory]=useState<CallResponse[]>([]),[mobileMenu,setMobileMenu]=useState(false),[message,setMessage]=useState("");
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem("actionbridge.history");if(raw)setHistory(JSON.parse(raw))}catch{} return()=>{if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>{try{localStorage.setItem("actionbridge.history",JSON.stringify(history.slice(0,25)))}catch{}},[history]);
 const completed=!!result&&(result.taskCompleted===true||result.status?.toLowerCase()==="completed");
 async function poll(id:string,attempt=0){try{const r=await fetch(`/api/calls/${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to read call status.");setResult(c=>({...c,...d,callId:id})); if(attempt<20){const er=await fetch(`/api/calls/${encodeURIComponent(id)}/events`,{cache:"no-store"});const ed=await er.json().catch(()=>({}));if(er.ok){const list=Array.isArray(ed)?ed:(Array.isArray(ed.events)?ed.events:[]);setEvents(list)}} const s=String(d.status||"").toLowerCase();if(!terminal.has(s)&&!d.taskCompleted&&attempt<30)timer.current=setTimeout(()=>poll(id,attempt+1),2500);else{setLoading(false);setHistory(h=>[{...d,callId:id},...h.filter(x=>x.callId!==id)].slice(0,25));setView("results")}}catch(e){setResult(c=>({...c,error:e instanceof Error?e.message:"Unable to read call."}));setLoading(false)}}
 async function submit(e:FormEvent){e.preventDefault();setMessage("");setResult(null);setEvents([]);setLoading(true);setView("calls");try{const r=await fetch("/api/calls",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal,phone,region,locale,approved})});const d=await r.json();if(!r.ok)throw Error(d.error||"The call could not be started.");setResult(d);if(d.callId)await poll(d.callId);else setLoading(false)}catch(e){setMessage(e instanceof Error?e.message:"Unexpected error");setResult({error:e instanceof Error?e.message:"Unexpected error"});setLoading(false)}}
 async function hangup(){if(!result?.callId)return;setMessage("Stopping call…");try{const r=await fetch(`/api/calls/${encodeURIComponent(result.callId)}/hangup`,{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to stop call.");setMessage("Stop request sent.");await poll(result.callId)}catch(e){setMessage(e instanceof Error?e.message:"Unable to stop call.")}}
 function newTask(){if(timer.current)clearTimeout(timer.current);setResult(null);setEvents([]);setApproved(false);setLoading(false);setMessage("");setView("task")}
 function navTo(v:View){setView(v);setMobileMenu(false)}
 const status=String(result?.status||(loading?"starting":"idle"));
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="mark"/><span>ActionBridge</span></div><div className="side-label">WORKSPACE</div>{nav.map(([id,icon,label])=><button key={id} className={`nav-item ${view===id?"active":""}`} onClick={()=>navTo(id)}><span>{icon}</span>{label}</button>)}<div className="side-bottom"><div className="live-dot"/> CALL-E / LIVE ACTION LAYER<br/><small>Human approval required</small></div></aside>
 <main className="main-area"><header className="mobile-top"><div className="brand"><span className="mark"/>ActionBridge</div><div className="mobile-actions"><span className="live-pill">LIVE</span><button className="menu-button" aria-label="Open navigation" onClick={()=>setMobileMenu(x=>!x)}>☰</button></div></header>{mobileMenu&&<nav className="mobile-nav">{nav.map(([id,icon,label])=><button key={id} className={view===id?"active":""} onClick={()=>navTo(id)}><span>{icon}</span>{label}</button>)}</nav>}
 {view==="overview"&&<section><div className="hero"><div className="eyebrow">REAL-WORLD ACTION ORCHESTRATION</div><h1>Turn intention into<br/><em>real-world action.</em></h1><p>ActionBridge transforms a goal into a controlled phone workflow, executes it through CALL-E, captures structured evidence, and keeps consequential actions behind explicit human approval.</p><button className="primary hero-btn" onClick={newTask}>Create a phone task <span>→</span></button></div><div className="dashboard-grid"><div className="metric-card"><span>ACTIVE TASK</span><strong>{loading?"01":"00"}</strong><small>{loading?"phone workflow running":"ready"}</small></div><div className="metric-card"><span>LAST RESULT</span><strong>{completed?"VERIFIED":"—"}</strong><small>{completed?"evidence available":"no verified task"}</small></div><div className="metric-card"><span>CONTROL</span><strong>HUMAN</strong><small>approval before every call</small></div></div><div className="feature-grid"><div className="feature"><b>01</b><h3>Understand</h3><p>Define the goal, recipient, locale and success criteria.</p></div><div className="feature"><b>02</b><h3>Execute</h3><p>CALL-E handles the real phone conversation and adapts to the response.</p></div><div className="feature"><b>03</b><h3>Verify</h3><p>Review completion, confidence, structured results and evidence before deciding next steps.</p></div></div></section>}
 {view==="task"&&<section className="content"><div className="page-head"><div><div className="eyebrow">01 / TASK WORKSPACE</div><h2>Create a phone task</h2><p>Start with one clear, bounded outcome.</p></div></div><div className="examples"><span>QUICK START</span>{examples.map(x=><button key={x} onClick={()=>setGoal(x)}>{x}</button>)}</div><form className="task-grid" onSubmit={submit}><div className="panel"><label htmlFor="goal">GOAL / SUCCESS CRITERIA</label><textarea id="goal" required minLength={12} maxLength={3000} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="What exactly should the AI phone agent accomplish?"/><div className="two-col"><div><label htmlFor="phone">RECIPIENT / E.164</label><input id="phone" required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+919876543210" inputMode="tel"/></div><div><label htmlFor="region">REGION</label><input id="region" required value={region} onChange={e=>setRegion(e.target.value.toUpperCase())} maxLength={2}/></div></div><label htmlFor="locale">LANGUAGE / LOCALE</label><input id="locale" required value={locale} onChange={e=>setLocale(e.target.value)} placeholder="en-IN or hi-IN"/><div className="notice"><b>Before you call:</b> this creates a real outbound phone action. The agent identifies itself as AI, stays within the task, and does not make unrelated consequential commitments.</div><label className="check"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> I authorize this specific phone call.</label><div className="actions"><button className="primary" disabled={!approved||loading}>{loading?"Running…":"Authorize & call →"}</button><button type="button" className="secondary" onClick={()=>{setGoal("");setPhone("")}}>Clear</button></div>{message&&<p className="error">{message}</p>}</div><div className="panel side-info"><div className="kicker">EXECUTION PLAN</div><div className="timeline"><span>1</span><div><b>Goal captured</b><small>Bounded objective and recipient</small></div><span>2</span><div><b>CALL-E prepared</b><small>Instructions + strict result schema</small></div><span>3</span><div><b>Live conversation</b><small>Events and state tracked</small></div><span>4</span><div><b>Evidence returned</b><small>Verification before decision</small></div></div></div></form></section>}
 {view==="calls"&&<section className="content"><div className="page-head"><div><div className="eyebrow">02 / EXECUTION</div><h2>Live Call Center</h2><p>Current state, events and safe stop control.</p></div>{result?.callId&&loading&&<button className="danger" onClick={hangup}>Stop call</button>}</div><div className="panel call-console">{result?<><div className="call-top"><div className="call-orb">◉</div><div><span className="live-pill">{loading?"CALL IN PROGRESS":status.toUpperCase()}</span><h3>{phone||"Recipient"}</h3><p>{goal||"Phone task"}</p></div></div><div className="call-progress"><span className={loading?"on":"done"}/><span className={!loading?"done":""}/><span className={completed?"done":""}/></div><div className="result-grid"><span>CALL ID</span><strong>{result.callId||"—"}</strong><span>STATUS</span><strong>{status}</strong><span>CONFIDENCE</span><strong>{typeof result.completionConfidence==="object"?JSON.stringify(result.completionConfidence):String(result.completionConfidence??"pending")}</strong><span>TASK</span><strong>{completed?"Verified":loading?"Executing":"Incomplete"}</strong></div><div className="events"><label>CALL EVENTS</label>{events.length?events.slice(-10).map((x,i)=><div className="event-row" key={String(x.id||i)}><span>{x.type||x.status||"event"}</span><small>{x.timestamp||x.message||""}</small></div>):<div className="event-empty">Waiting for CALL-E events…</div>}</div>{result.error&&<p className="error">{result.error}</p>}{message&&<p className="error">{message}</p>}</>:<div className="empty"><div>◉</div><h3>No active call</h3><p>Create and authorize a task to start a real phone workflow.</p><button className="primary" onClick={newTask}>Create task</button></div>}</div></section>}
 {view==="results"&&<section className="content"><div className="page-head"><div><div className="eyebrow">03 / VERIFICATION</div><h2>Results & Evidence</h2><p>Review the machine result before taking any consequential action.</p></div></div><div className="panel evidence"><div className="result-grid"><span>COMPLETION</span><strong>{completed?"VERIFIED":"PENDING"}</strong><span>CONFIDENCE</span><strong>{typeof result?.completionConfidence==="object"?JSON.stringify(result?.completionConfidence):String(result?.completionConfidence??"—")}</strong><span>CALL ID</span><strong>{result?.callId||"—"}</strong></div><div className="json-grid"><div><label>STRUCTURED RESULT</label><pre>{JSON.stringify(result?.structuredResult??{message:"Complete a call to receive structured results."},null,2)}</pre></div><div><label>EVIDENCE</label><pre>{JSON.stringify(result?.evidence??{message:"Evidence will appear after CALL-E returns it."},null,2)}</pre></div></div><div className="decision"><div><b>Human decision gate</b><p>ActionBridge does not automatically make a consequential follow-up decision from this result.</p></div><button className="secondary" onClick={newTask}>Create another task</button></div></div></section>}
 {view==="history"&&<section className="content"><div className="page-head"><div><div className="eyebrow">04 / LOCAL HISTORY</div><h2>Task History</h2><p>Recent verified call outcomes stored in this browser.</p></div></div><div className="panel table">{history.length?history.map((x,i)=><div className="history-row" key={x.callId||i}><span className="history-icon">◉</span><div><b>{x.callId||"Call"}</b><small>{x.status||"unknown"}</small></div><strong>{x.taskCompleted?"Verified":"Incomplete"}</strong></div>):<div className="empty"><div>↺</div><h3>No history yet</h3><p>Completed tasks will appear here. This browser-only history is not a server audit log.</p></div>}</div></section>}
 {view==="settings"&&<section className="content"><div className="page-head"><div><div className="eyebrow">05 / CONTROL</div><h2>Settings & Safety</h2><p>Product safety boundaries and runtime configuration.</p></div></div><div className="settings-grid"><div className="panel setting"><b>Human approval</b><span>Required before every real phone call.</span><i>ENABLED</i></div><div className="panel setting"><b>AI disclosure</b><span>Caller is instructed to identify itself as AI.</span><i>ENABLED</i></div><div className="panel setting"><b>Server credentials</b><span>CALL-E credentials are never exposed to browser JavaScript.</span><i>ENABLED</i></div><div className="panel setting"><b>Bounded execution</b><span>Task instructions prohibit unrelated financial, legal or other consequential commitments.</span><i>ENABLED</i></div><div className="panel setting"><b>Browser history</b><span>Recent results are kept locally for convenience. Production multi-user persistence requires a database/auth provider.</span><i>LOCAL ONLY</i></div><div className="panel setting"><b>Webhook verification</b><span>Set CALLE_WEBHOOK_SECRET in Vercel and configure the same secret with the webhook integration.</span><i>CONFIGURABLE</i></div></div></section>}
 {view==="docs"&&<section className="content"><div className="page-head"><div><div className="eyebrow">06 / DOCUMENTATION</div><h2>How ActionBridge works</h2><p>Goal-driven phone work with evidence and human control.</p></div></div><div className="docs"><article><span>01</span><h3>Understand</h3><p>Define the goal, recipient, region, language and success criteria. Quick-start examples help create a safe first task.</p></article><article><span>02</span><h3>Execute with CALL-E</h3><p>The server sends a bounded task and strict structured result schema to CALL-E. Credentials stay server-side.</p></article><article><span>03</span><h3>Observe</h3><p>ActionBridge reads call status and developer-facing events, and provides a controlled hangup endpoint for active calls.</p></article><article><span>04</span><h3>Verify</h3><p>Completion, confidence, structured results and evidence are surfaced before a human decides what happens next.</p></article></div></section>}
 </main></div>}
